# Site Settings
title: DrakeJin 
email: dydwls121200@gmail.com
description: 세상을 재미있게 만들기 위한 기술
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://blog.drakejin.me" # the base hostname & protocol for your site
url: "http://localhost:3000" # the base hostname & protocol for your site
google_analytics: "UA-90708702-1"

# User Settings
username: DrakeJin
user_description: 재미없으면 하기 싫어욧.
disqus_username: blog-drakejin-me

# Social Media
# Remove the item if you don't need it
github_username: drake-jin
facebook_username: drakejin
# twitter_username: twitter_username
# instagram_username: instagram_username
linkedin_username: drakejin
medium_username: dydwls121200

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: 홈
    url: /
  - title: 블로그 소개
    url: /about
  - title: 나
    url: /me
  - title: 질문?
    url: /contact

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
